CREATE TABLE [AddressesDirectory]
(
	ID INT PRIMARY KEY IDENTITY,
	CityID INT NULL,
	Street NVARCHAR(100) NOT NULL,
	Home NVARCHAR(40) NOT NULL,
	Fiat NVARCHAR(40) NOT NULL,
	IsDeleted bit NOT NULL DEFAULT (0),

	CONSTRAINT FK_AddressesDirectory_fs_city FOREIGN KEY ([CityID]) REFERENCES [fs_city] ([id]) ON UPDATE CASCADE ON DELETE SET NULL
)